### ISSUE TITLE
Click on New project aborts in Linux (Ubuntu Xenial)

### ISSUE THREAD

**Issue by uberhacker** [mglaman/conductor#23] opened 2016-10-27 21:26 UTC
If I click on `New project` after starting conductor, it aborts with the following message:
```
> conductor@0.1.3 start /home/ed/conductor
> electron .

Gtk-Message: Failed to load module "overlay-scrollbar"
[5812:1027/162421:FATAL:render_process_host_impl.cc(573)] Check failed: !BrowserMainRunner::ExitedMainMessageLoop(). 
#0 0x000001e4836e <unknown>
#1 0x000001e5e06b <unknown>
#2 0x000002911d80 <unknown>
#3 0x0000029c3ea6 <unknown>
#4 0x0000029fecf3 <unknown>
#5 0x0000029f421a <unknown>
#6 0x0000029f413b <unknown>
#7 0x0000034e0424 atom::api::WebContents::WebContents()
#8 0x0000034e9376 atom::api::WebContents::Create()
#9 0x0000034f9d15 atom::api::Window::Window()
#10 0x0000034fb4fe atom::api::Window::New()
#11 0x0000034c218c mate::internal::InvokeNew<>()
#12 0x0000034c231f mate::internal::Dispatcher<>::DispatchToCallback()
#13 0x7fbe71dca628 v8::internal::FunctionCallbackArguments::Call()
#14 0x7fbe71e2857c <unknown>
#15 0x11d71fe06147 <unknown>
```

**Comment by mglaman** [comment] 2016-10-27 21:52
Marking as dupe of #9

**Closed by mglaman** 2016-10-27 21:52 UTC
Labels: bug, duplicate, Linux

**Comment by uberhacker** [comment] 2016-10-28 00:22
@mglaman: Technically, this could be a separate issue as the other issue is referencing an existing project.

**Comment by mglaman** [comment] 2016-10-28 00:24
The issue isn't which button, but rather a crash on trying to open a new window

**Comment by uberhacker** [comment] 2016-10-28 00:31
Ah, a general issue makes sense.  Let me know if I can help with debugging or testing.  I'm liking this project.

**Comment by mglaman** [comment] 2016-10-28 01:18
@uberhacker testing is huge. and ideas. one of the next steps is to provide better feedback from Composer output. But I have had to focus on "do the executables actually install?"

**Comment by uberhacker** [comment] 2016-10-28 01:22
Here is an idea: create binaries!  Someone recently introduced me to this amazing project: https://github.com/jordansissel/fpm.

**Comment by mglaman** [comment] 2016-10-28 01:24
@uberhacker I just opened #25 and there is #18.

Releases have .dev, .AppImage, mac ZIP and dmg and Windows exe https://github.com/mglaman/conductor/releases

**Comment by uberhacker** [comment] 2016-10-28 01:30
Wow, how did I miss those? LoL  Just out of curiosity, how are you generating those binaries?  Do you have an automated process that outputs everything on the fly?

**Comment by mglaman** [comment] 2016-10-28 03:29
https://github.com/electron-userland/electron-builder

Electron Builder handles all the packaging. It can detect if running on CI and if you have a GitHub token configured it uploads. _magic_

**Comment by uberhacker** [comment] 2016-10-28 04:11
That is ... awesomesauce.
